### PR TITLE
Simplify build process

### PR DESCRIPTION
**Pull request by rkoeninger**
install.lsp no longer requires *.kl files in be in root directory, it just reads them out of the klambda/ directory instead and does not delete them after build, and creates Native/ directory if missing.

Also, some cleanup of install.lsp.

### CODE REVIEW

**Comment by tizoc** [comment]
@rkoeninger from where does `LISP-IMPLEMENTATION-VERSION` come from?

**Comment by tizoc** [comment]
Nevermind, found it.

**Comment by tizoc** [comment]
@rkoeninger looks good, is there anything else you were going to do or is is ready for merging already?

**Comment by rkoeninger** [comment]
@tizoc I was considering doing more (making install.lsp only generate files under Native/) but this is fine for now.

**Pull request merged**
